# Generated by Django 4.2.7 on 2026-05-05 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('DOCTOR', 'Doctor'), ('EQUIPMENT', 'Equipment'), ('FACILITY', 'Facility'), ('EVENT', 'Event')], default='HOSPITAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('GENERAL', 'General Ophthalmologist'), ('CATARACT', 'Cataract & Refractive Care'), ('RETINA', 'Vitreo Retina Specialist'), ('GLAUCOMA', 'Glaucoma Specialist'), ('OCULOPLASTY', 'Oculoplasty Specialist'), ('PEDIATRIC', 'Pediatric Ophthalmologist'), ('CORNEA', 'Cornea Specialist')], max_length=20)),
                ('qualification', models.CharField(max_length=200)),
                ('experience_years', models.IntegerField(default=0)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('monday_available', models.BooleanField(default=True)),
                ('tuesday_available', models.BooleanField(default=True)),
                ('wednesday_available', models.BooleanField(default=True)),
                ('thursday_available', models.BooleanField(default=True)),
                ('friday_available', models.BooleanField(default=True)),
                ('saturday_available', models.BooleanField(default=True)),
                ('sunday_available', models.BooleanField(default=False)),
                ('start_time', models.TimeField(default='09:00:00')),
                ('end_time', models.TimeField(default='17:00:00')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['user__first_name'],
            },
        ),
    ]
